apiVersion: v1
kind: Secret
metadata:
  name: gastos-secrets
type: Opaque
stringData:
  POSTGRES_USER: "gastos_user"
  POSTGRES_PASSWORD: "gastos_pass"
  JWT_SECRET: "cambia_este_jwt_secret_super_seguro"